trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'macOS-latest'  # iOS builds require macOS
  
variables:
  - group: AppDistributionSecrets
  
stages:

# =========================
# STAGE 1: Build IPA
# =========================
- stage: Build
  jobs:
    - job: BuildIPA
      steps:
        # Install Flutter
        - task: FlutterInstall@0
          inputs:
            mode: 'auto'
            channel: 'stable'
            version: 'latest'

        # Setup Flutter environment
        - script: |
            export PATH="$FLUTTER_HOME/bin:$PATH"
            flutter --version
            flutter pub get
          displayName: 'Setup Flutter & Run Diagnostics'
        
        # Install Apple Distribution Certificate
        - task: InstallAppleCertificate@2
          inputs:
            certSecureFile: 'Distripution Certificates.p12'  
            certPwd: $(certificate_pass)
        
        # Install Apple Provisioning Profile
        - task: InstallAppleProvisioningProfile@1
          inputs:
            provisioningProfileLocation: 'secureFiles'  
            provProfileSecureFile: 'Pipeline_test_ADHOC.mobileprovision'  
                
        # Build iOS IPA
        - script: |
            export PATH="$FLUTTER_HOME/bin:$PATH"
            flutter build ipa --release 
          displayName: 'Build iOS IPA'

        # Copy artifacts (ipa file)
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/build/ios/ipa'  
            Contents: '**/*.ipa'  
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        # Publish IPA as artifact
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'release-ipa'
            publishLocation: 'Container'
